# [Unused Internal connection for Host -> Enclave communication
internal_host_to_enclave_url = "https://0.0.0.0:50054"

# Internal connection for Enclave -> Host communication
internal_enclave_to_host_url = "https://0.0.0.0:50053"

# Untrusted connection for Client -> Enclave communication
client_to_enclave_untrusted_url = "https://0.0.0.0:50052"

# Attested connection for Client -> Enclave communication
client_to_enclave_attested_url = "https://0.0.0.0:50051"

# Max model size in bytes (default value: 500mb)
max_model_size = 524288000

# Max input size in bytes (default value: 500mb)
max_input_size = 524288000

# Set the path
models_path = "/workspaces/blindai/server/bin/models"